/// Contains all the headers necessary to use the Insound Core library
#pragma once

#include "core/AudioDevice.h"
#include "core/AudioLoader.h"
#include "core/BufferView.h"
#include "core/Bus.h"
#include "core/Command.h"
#include "core/Engine.h"
#include "core/Effect.h"
#include "core/effects.h"
#include "core/Error.h"
#include "core/Handle.h"
#include "core/logging.h"
#include "core/Marker.h"
#include "core/MultiPool.h"
#include "core/PCMSource.h"
#include "core/PerfTimer.h"
#include "core/Pool.h"
#include "core/SampleFormat.h"
#include "core/SoundBuffer.h"
#include "core/Source.h"
#include "core/SourceRef.h"
#include "core/SourceRefFwd.h"
#include "core/TimeUnit.h"
#include "core/util.h"
